# docker-compose.yml
version: '3.8'

networks:
  micro_network:
    external:
      name: micro_network

services:
  kst-api:
    container_name: kst-service
    build:
      context: .
    ports:
    - "5003:5003"
    networks:
      - micro_network
    restart: always
